## Prepare a classification model using SVM for salary data 

In [1]:
# import numpy as np
import pandas as pd
# from sklearn import preprocessing
from sklearn import metrics
# import seaborn as sns
# from sklearn.svm import SVC
# from sklearn.model_selection import train_test_split
# from matplotlib import pyplot as plt
# from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
# from sklearn import preprocessing

### Data collection and description

In [2]:
train=pd.read_csv("data/SalaryData_Train.csv")
test=pd.read_csv("data/SalaryData_Test.csv")

In [3]:
columns=["age","workclass","education","educationno","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hoursperweek","native","Salary"]

In [4]:
train

age          workclass      education  educationno  \
0       39          State-gov      Bachelors           13   
1       50   Self-emp-not-inc      Bachelors           13   
2       38            Private        HS-grad            9   
3       53            Private           11th            7   
4       28            Private      Bachelors           13   
...    ...                ...            ...          ...   
25301   39       Self-emp-inc     Assoc-acdm           12   
25302   35            Private      Assoc-voc           11   
25303   33            Private           11th            7   
25304   31            Private   Some-college           10   
25305   49            Private   Some-college           10   

             maritalstatus          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
25301   Married-civ-spouse               Sales         Husband   White   
25302        Never-married        Craft-repair       Own-child   Black   
25303        Never-married   Handlers-cleaners       Own-child   Black   
25304        Never-married        Craft-repair   Not-in-family   White   
25305   Married-civ-spouse      Prof-specialty         Husband   White   

           sex  capitalgain  capitalloss  hoursperweek          native  Salary  
0         Male       2174.0          0.0          40.0   United-States   <=50K  
1         Male          0.0          0.0          13.0   United-States   <=50K  
2         Male          0.0          0.0          40.0   United-States   <=50K  
3         Male          0.0          0.0          40.0   United-States   <=50K  
4       Female          0.0          0.0          40.0            Cuba   <=50K  
...        ...          ...          ...           ...             ...     ...  
25301     Male       5178.0          0.0          48.0   United-States    >50K  
25302     Male          0.0          0.0          40.0   United-States   <=50K  
25303     Male          0.0          0.0          40.0   United-States   <=50K  
25304     Male          0.0          0.0          46.0   United-States   <=50K  
25305      NaN          NaN          NaN           NaN             NaN     NaN  

[25306 rows x 14 columns]

In [5]:
test

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

### EDA (Exploratory Data Analysis)

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25306 entries, 0 to 25305
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   age            25306 non-null  int64  
 1   workclass      25306 non-null  object 
 2   education      25306 non-null  object 
 3   educationno    25306 non-null  int64  
 4   maritalstatus  25306 non-null  object 
 5   occupation     25306 non-null  object 
 6   relationship   25306 non-null  object 
 7   race           25306 non-null  object 
 8   sex            25305 non-null  object 
 9   capitalgain    25305 non-null  float64
 10  capitalloss    25305 non-null  float64
 11  hoursperweek   25305 non-null  float64
 12  native         25305 non-null  object 
 13  Salary         25305 non-null  object 
dtypes: float64(3), int64(2), object(9)
memory usage: 2.7+ MB


In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [8]:
train.describe()

age  educationno   capitalgain   capitalloss  hoursperweek
count  25306.000000  25306.00000  25305.000000  25305.000000  25305.000000
mean      38.478108     10.12499   1102.215491     87.784944     40.897767
std       13.172556      2.54356   7502.590476    403.231910     11.944026
min       17.000000      1.00000      0.000000      0.000000      1.000000
25%       28.000000      9.00000      0.000000      0.000000     40.000000
50%       37.000000     10.00000      0.000000      0.000000     40.000000
75%       47.000000     13.00000      0.000000      0.000000     45.000000
max       90.000000     16.00000  99999.000000   4356.000000     99.000000

In [9]:
test.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  15060.000000  15060.000000  15060.000000  15060.000000  15060.000000
mean      38.768327     10.112749   1120.301594     89.041899     40.951594
std       13.380676      2.558727   7703.181842    406.283245     12.062831
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       48.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [10]:
train.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              1
capitalgain      1
capitalloss      1
hoursperweek     1
native           1
Salary           1
dtype: int64

In [11]:
test.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [12]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [13]:
train= train.apply(LabelEncoder().fit_transform)
train

age  workclass  education  educationno  maritalstatus  occupation  \
0       22          5          9           12              4           0   
1       33          4          9           12              2           3   
2       21          2         11            8              0           5   
3       36          2          1            6              2           5   
4       11          2          9           12              2           9   
...    ...        ...        ...          ...            ...         ...   
25301   22          3          7           11              2          11   
25302   18          2          8           10              4           2   
25303   16          2          1            6              4           5   
25304   14          2         15            9              4           2   
25305   32          2         15            9              2           9   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1           22            0            39   
1                 0     4    1            0            0            12   
2                 1     4    1            0            0            39   
3                 0     2    1            0            0            39   
4                 5     2    0            0            0            39   
...             ...   ...  ...          ...          ...           ...   
25301             0     4    1           74            0            47   
25302             3     2    1            0            0            39   
25303             3     2    1            0            0            39   
25304             1     4    1            0            0            45   
25305             0     4    2          114           87            94   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
25301      37       1  
25302      37       0  
25303      37       0  
25304      37       0  
25305      40       2  

[25306 rows x 14 columns]

In [14]:
test= test.apply(LabelEncoder().fit_transform)
test

age  workclass  education  educationno  maritalstatus  occupation  \
0        8          2          1            6              4           6   
1       21          2         11            8              2           4   
2       11          1          7           11              2          10   
3       27          2         15            9              2           6   
4       17          2          0            5              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   16          2          9           12              4           9   
15056   22          2          9           12              0           9   
15057   21          2          9           12              2           9   
15058   27          2          9           12              0           0   
15059   18          3          9           12              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            39   
1                 0     4    1            0            0            49   
2                 0     4    1            0            0            39   
3                 0     2    1           87            0            39   
4                 1     4    1            0            0            29   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            39   
15056             1     4    0            0            0            35   
15057             0     4    1            0            0            49   
15058             3     1    1           73            0            39   
15059             0     4    1            0            0            59   

       native  Salary  
0          37       0  
1          37       0  
2          37       1  
3          37       1  
4          37       0  
...       ...     ...  
15055      37       0  
15056      37       0  
15057      37       0  
15058      37       0  
15059      37       1  

[15060 rows x 14 columns]

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25306 entries, 0 to 25305
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            25306 non-null  int64
 1   workclass      25306 non-null  int32
 2   education      25306 non-null  int32
 3   educationno    25306 non-null  int64
 4   maritalstatus  25306 non-null  int32
 5   occupation     25306 non-null  int32
 6   relationship   25306 non-null  int32
 7   race           25306 non-null  int32
 8   sex            25306 non-null  int32
 9   capitalgain    25306 non-null  int64
 10  capitalloss    25306 non-null  int64
 11  hoursperweek   25306 non-null  int64
 12  native         25306 non-null  int32
 13  Salary         25306 non-null  int32
dtypes: int32(9), int64(5)
memory usage: 1.8 MB


In [16]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  int32
 2   education      15060 non-null  int32
 3   educationno    15060 non-null  int64
 4   maritalstatus  15060 non-null  int32
 5   occupation     15060 non-null  int32
 6   relationship   15060 non-null  int32
 7   race           15060 non-null  int32
 8   sex            15060 non-null  int32
 9   capitalgain    15060 non-null  int64
 10  capitalloss    15060 non-null  int64
 11  hoursperweek   15060 non-null  int64
 12  native         15060 non-null  int32
 13  Salary         15060 non-null  int32
dtypes: int32(9), int64(5)
memory usage: 1.1 MB


In [17]:
x_train = train.drop(['maritalstatus','sex','native','race','relationship','Salary'],axis=1).values
y_train = train['Salary'].values

In [18]:
x_train

array([[ 22,   5,   9, ...,  22,   0,  39],
       [ 33,   4,   9, ...,   0,   0,  12],
       [ 21,   2,  11, ...,   0,   0,  39],
       ...,
       [ 16,   2,   1, ...,   0,   0,  39],
       [ 14,   2,  15, ...,   0,   0,  45],
       [ 32,   2,  15, ..., 114,  87,  94]], dtype=int64)

In [19]:
y_train

array([0, 0, 0, ..., 0, 0, 2])

In [20]:
x_test = test.drop(['maritalstatus','sex','native','race','relationship','Salary'],axis=1).values
y_test = test['Salary'].values

In [21]:
x_test

array([[ 8,  2,  1, ...,  0,  0, 39],
       [21,  2, 11, ...,  0,  0, 49],
       [11,  1,  7, ...,  0,  0, 39],
       ...,
       [21,  2,  9, ...,  0,  0, 49],
       [27,  2,  9, ..., 73,  0, 39],
       [18,  3,  9, ...,  0,  0, 59]], dtype=int64)

In [22]:
y_test

array([0, 0, 1, ..., 0, 0, 1])

In [23]:
number = preprocessing.LabelEncoder()
for i in columns:
    train[i] = number.fit_transform(train[i])
    test[i] = number.fit_transform(test[i])

colnames = train.columns

In [24]:
trainx = train[colnames[0:13]]
trainy = train[colnames[13]]
testx = test[colnames[0:13]]
testy  = test[colnames[13]]

In [25]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [26]:
trainx = norm_func(trainx)
testx =  norm_func(testx)

### SVM (Support Vector Machine )

1) Linear

In [27]:
from sklearn.svm import SVC
model_linear = SVC(kernel = "linear")
model_linear.fit(trainx,trainy)
pred_test_linear = model_linear.predict(testx)
print("Accuracy:",metrics.accuracy_score(testy, pred_test_linear))

Accuracy: 0.8072377158034528


2) Poly

In [28]:
model_poly = SVC(kernel = "poly",gamma="auto")
model_poly.fit(trainx,trainy)
pred_test_poly = model_poly.predict(testx)
print("Accuracy:",metrics.accuracy_score(testy, pred_test_poly))

Accuracy: 0.8266932270916335


3) RBF

In [29]:
model_rbf = SVC(kernel = "rbf",gamma="auto")
model_rbf.fit(trainx,trainy)
pred_test_rbf = model_rbf.predict(testx)
print("Accuracy:",metrics.accuracy_score(testy, pred_test_rbf))

Accuracy: 0.8167994687915007


In [30]:
from sklearn.metrics import classification_report
model=SVC()
model.fit(trainx,trainy)
pred=model.predict(testx)
print(classification_report(pred,testy))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89     11783
           1       0.61      0.69      0.65      3277

    accuracy                           0.84     15060
   macro avg       0.76      0.78      0.77     15060
weighted avg       0.84      0.84      0.84     15060

